import { WS_CONNECTION_START_ORDERS_USER,
    WS_CONNECTION_SUCCESS_ORDERS_USER,
    WS_CONNECTION_ERROR_ORDERS_USER,
    WS_CONNECTION_CLOSED_ORDERS_USER,
    WS_GET_ORDERS_USER,
 } from "../services/order-user/actions";

 import { WS_CONNECTION_START_FEED_ORDERS,
   WS_CONNECTION_SUCCESS_FEED_ORDERS,
   WS_CONNECTION_ERROR_FEED_ORDERS,
   WS_CONNECTION_CLOSED_FEED_ORDERS,
   WS_GET_FEED_ORDERS,
} from "../services/feed-orders/actions";


 export const wsActionsOrdersUser = {
    wsInit: WS_CONNECTION_START_ORDERS_USER,
    onOpen: WS_CONNECTION_SUCCESS_ORDERS_USER,
    onClose: WS_CONNECTION_CLOSED_ORDERS_USER,
    onError: WS_CONNECTION_ERROR_ORDERS_USER,
    onMessage: WS_GET_ORDERS_USER
  };

  export const wsActionsFeedOrders = {
   wsInit: WS_CONNECTION_START_FEED_ORDERS,
   onOpen: WS_CONNECTION_SUCCESS_FEED_ORDERS,
   onClose: WS_CONNECTION_CLOSED_FEED_ORDERS,
   onError: WS_CONNECTION_ERROR_FEED_ORDERS,
   onMessage: WS_GET_FEED_ORDERS
 };